### ISSUE TITLE
VS Code Pytest Discovery Error

### ISSUE THREAD

**Issue by ralvarezingram** [cloudblue/connect-extension-runner#174]
After version 28.5 installation, pytest discovery error in VScode:

![Captura de pantalla 2023-07-21 a las 17 17 57](https://github.com/cloudblue/connect-extension-runner/assets/109272318/3565cc68-fd79-4677-b34f-85d8438662ad)

Installing "libsqlite3-dev" library on Docker image solves the problem in my case.

RUN apt-get update && apt-get install -y --no-install-recommends \
  && apt-get install -y libsqlite3-dev

**Comment by ffaraone** [comment]
Fixed in 28.7.
